# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/smartfileorganizer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/smartfileorganizer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/smartfileorganizer/CMakeFiles /workspaces/smartfileorganizer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/smartfileorganizer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sfo

# Build rule for target.
sfo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sfo
.PHONY : sfo

# fast build rule for target.
sfo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfo.dir/build.make CMakeFiles/sfo.dir/build
.PHONY : sfo/fast

src/backup.o: src/backup.c.o
.PHONY : src/backup.o

# target to build an object file
src/backup.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfo.dir/build.make CMakeFiles/sfo.dir/src/backup.c.o
.PHONY : src/backup.c.o

src/backup.i: src/backup.c.i
.PHONY : src/backup.i

# target to preprocess a source file
src/backup.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfo.dir/build.make CMakeFiles/sfo.dir/src/backup.c.i
.PHONY : src/backup.c.i

src/backup.s: src/backup.c.s
.PHONY : src/backup.s

# target to generate assembly for a file
src/backup.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfo.dir/build.make CMakeFiles/sfo.dir/src/backup.c.s
.PHONY : src/backup.c.s

src/cli.o: src/cli.c.o
.PHONY : src/cli.o

# target to build an object file
src/cli.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfo.dir/build.make CMakeFiles/sfo.dir/src/cli.c.o
.PHONY : src/cli.c.o

src/cli.i: src/cli.c.i
.PHONY : src/cli.i

# target to preprocess a source file
src/cli.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfo.dir/build.make CMakeFiles/sfo.dir/src/cli.c.i
.PHONY : src/cli.c.i

src/cli.s: src/cli.c.s
.PHONY : src/cli.s

# target to generate assembly for a file
src/cli.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfo.dir/build.make CMakeFiles/sfo.dir/src/cli.c.s
.PHONY : src/cli.c.s

src/file_type_detection/file_type_detector.o: src/file_type_detection/file_type_detector.c.o
.PHONY : src/file_type_detection/file_type_detector.o

# target to build an object file
src/file_type_detection/file_type_detector.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfo.dir/build.make CMakeFiles/sfo.dir/src/file_type_detection/file_type_detector.c.o
.PHONY : src/file_type_detection/file_type_detector.c.o

src/file_type_detection/file_type_detector.i: src/file_type_detection/file_type_detector.c.i
.PHONY : src/file_type_detection/file_type_detector.i

# target to preprocess a source file
src/file_type_detection/file_type_detector.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfo.dir/build.make CMakeFiles/sfo.dir/src/file_type_detection/file_type_detector.c.i
.PHONY : src/file_type_detection/file_type_detector.c.i

src/file_type_detection/file_type_detector.s: src/file_type_detection/file_type_detector.c.s
.PHONY : src/file_type_detection/file_type_detector.s

# target to generate assembly for a file
src/file_type_detection/file_type_detector.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfo.dir/build.make CMakeFiles/sfo.dir/src/file_type_detection/file_type_detector.c.s
.PHONY : src/file_type_detection/file_type_detector.c.s

src/file_type_detection/sound_files/get_sound_file_info.o: src/file_type_detection/sound_files/get_sound_file_info.c.o
.PHONY : src/file_type_detection/sound_files/get_sound_file_info.o

# target to build an object file
src/file_type_detection/sound_files/get_sound_file_info.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfo.dir/build.make CMakeFiles/sfo.dir/src/file_type_detection/sound_files/get_sound_file_info.c.o
.PHONY : src/file_type_detection/sound_files/get_sound_file_info.c.o

src/file_type_detection/sound_files/get_sound_file_info.i: src/file_type_detection/sound_files/get_sound_file_info.c.i
.PHONY : src/file_type_detection/sound_files/get_sound_file_info.i

# target to preprocess a source file
src/file_type_detection/sound_files/get_sound_file_info.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfo.dir/build.make CMakeFiles/sfo.dir/src/file_type_detection/sound_files/get_sound_file_info.c.i
.PHONY : src/file_type_detection/sound_files/get_sound_file_info.c.i

src/file_type_detection/sound_files/get_sound_file_info.s: src/file_type_detection/sound_files/get_sound_file_info.c.s
.PHONY : src/file_type_detection/sound_files/get_sound_file_info.s

# target to generate assembly for a file
src/file_type_detection/sound_files/get_sound_file_info.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfo.dir/build.make CMakeFiles/sfo.dir/src/file_type_detection/sound_files/get_sound_file_info.c.s
.PHONY : src/file_type_detection/sound_files/get_sound_file_info.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfo.dir/build.make CMakeFiles/sfo.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfo.dir/build.make CMakeFiles/sfo.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfo.dir/build.make CMakeFiles/sfo.dir/src/main.c.s
.PHONY : src/main.c.s

src/organize.o: src/organize.c.o
.PHONY : src/organize.o

# target to build an object file
src/organize.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfo.dir/build.make CMakeFiles/sfo.dir/src/organize.c.o
.PHONY : src/organize.c.o

src/organize.i: src/organize.c.i
.PHONY : src/organize.i

# target to preprocess a source file
src/organize.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfo.dir/build.make CMakeFiles/sfo.dir/src/organize.c.i
.PHONY : src/organize.c.i

src/organize.s: src/organize.c.s
.PHONY : src/organize.s

# target to generate assembly for a file
src/organize.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfo.dir/build.make CMakeFiles/sfo.dir/src/organize.c.s
.PHONY : src/organize.c.s

src/utils.o: src/utils.c.o
.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfo.dir/build.make CMakeFiles/sfo.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfo.dir/build.make CMakeFiles/sfo.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sfo.dir/build.make CMakeFiles/sfo.dir/src/utils.c.s
.PHONY : src/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sfo"
	@echo "... src/backup.o"
	@echo "... src/backup.i"
	@echo "... src/backup.s"
	@echo "... src/cli.o"
	@echo "... src/cli.i"
	@echo "... src/cli.s"
	@echo "... src/file_type_detection/file_type_detector.o"
	@echo "... src/file_type_detection/file_type_detector.i"
	@echo "... src/file_type_detection/file_type_detector.s"
	@echo "... src/file_type_detection/sound_files/get_sound_file_info.o"
	@echo "... src/file_type_detection/sound_files/get_sound_file_info.i"
	@echo "... src/file_type_detection/sound_files/get_sound_file_info.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/organize.o"
	@echo "... src/organize.i"
	@echo "... src/organize.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

