#define FILE_NOT_FOUND 4041
#define FAILED_INIT_MAGIC 4042
#define FAILED_LOAD_MAGIC_DATABASE 4043
#define FAILED_GET_MIME_TYPE 4044

// Defines from organize module
#define ERROR_ON_ORGANIZE_DIR   -1
#define SUCCESS_ON_ORGANIZE_DIR  0
#define ERROR_ON_HANDLE_TYPE    -1
#define SUCCESS_ON_HANDLE_TYPE   0

// Defines from ocli module
#define  USER_COMMAND_READ_ERROR  -1
#define  USER_COMMAND_READ_SUCCESS 0